[project]
name = "mm-build-test-devices"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "ipython>=9.2.0",
    "meson-python>=0.18.0",
    "ninja>=1.11.1.4",
    "rich>=14.0.0",
    "ruff>=0.11.9",
]
