name: CI

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows-latest'
        with:
          toolset: "14.29"

      - name: install boost
        if: matrix.os == 'windows-latest'
        run: choco install boost-msvc-14.2

      - name: install
        shell: bash
        run: |
          uv run make
          ls -la
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mm-test-adapters-${{ matrix.os }}
          path: adapters
